# Generated by Django 3.2.15 on 2022-09-22 12:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=70)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('company_type', models.CharField(choices=[('1', 'ŞAHIS'), ('2', 'Büyük işletme'), ('3', 'KOBİ'), ('4', 'STK')], max_length=1, verbose_name='Company Type')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('web_site', models.CharField(blank=True, max_length=200, null=True)),
                ('company_employee_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
